// Web-Fundamentals/Web3/DappProject2.0/frontend/src/components/DeployERC721.vue
<template>
  <div class="bg-white shadow rounded-lg p-6 max-w-2xl mx-auto">
    <h3 class="text-xl font-bold mb-6 text-gray-900">Deploy ERC721 NFT</h3>
    <form @submit.prevent="deployNFT" class="space-y-4">
      <div>
        <label for="collectionName" class="block text-sm font-medium text-gray-700 mb-1">Collection Name</label>
        <input 
          type="text" 
          id="collectionName" 
          v-model="collectionName" 
          placeholder="e.g. My NFT Collection"
          class="block w-full px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-gray-900 placeholder-gray-400" 
          required
        >
      </div>
      <div>
        <label for="collectionSymbol" class="block text-sm font-medium text-gray-700 mb-1">Collection Symbol</label>
        <input 
          type="text" 
          id="collectionSymbol" 
          v-model="collectionSymbol" 
          placeholder="e.g. NFT"
          class="block w-full px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-gray-900 placeholder-gray-400" 
          required
        >
      </div>
      <div>
        <label for="baseURI" class="block text-sm font-medium text-gray-700 mb-1">Base URI (Optional)</label>
        <input 
          type="url" 
          id="baseURI" 
          v-model="baseURI" 
          placeholder="https://api.example.com/metadata/"
          class="block w-full px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-gray-900 placeholder-gray-400" 
        >
        <p class="mt-1 text-xs text-gray-500">Token IDs will be appended to this URI</p>
      </div>
      <button 
        type="submit" 
        :disabled="isDeploying"
        class="w-full flex justify-center py-3 px-4 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-indigo-400 transition-colors"
      >
        {{ isDeploying ? 'Deploying...' : 'Deploy' }}
      </button>
    </form>

    <div v-if="error" class="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
      <p class="text-red-700">{{ error }}</p>
    </div>

    <div v-if="lastDeployedAddress" class="mt-6 p-4 bg-green-50 border border-green-200 rounded-lg">
      <p class="text-green-800 font-medium">Deployment Success!</p>
      <p class="text-green-600 text-sm break-all font-mono mt-1">{{ lastDeployedAddress }}</p>
    </div>

    <div v-if="userERC721s.length > 0" class="mt-10 pt-6 border-t border-gray-100">
      <h4 class="text-lg font-semibold text-gray-900 mb-4">Your Deployed NFTs (Local)</h4>
      <div class="space-y-3">
        <div 
          v-for="contract in userERC721s" 
          :key="contract.contractAddress"
          @click="selectContract(contract.contractAddress)"
          class="p-4 rounded-xl border border-gray-200 hover:border-purple-400 hover:bg-purple-50 cursor-pointer transition-all flex justify-between items-center"
          :class="{ 'border-purple-600 bg-purple-50': selectedAddress === contract.contractAddress }"
        >
          <div class="flex flex-col">
            <span class="text-gray-900 font-medium">{{ contract.name }} ({{ contract.symbol }})</span>
            <span class="text-xs text-gray-500 font-mono">{{ contract.contractAddress }}</span>
          </div>
          <span v-if="selectedAddress === contract.contractAddress" class="text-xs font-semibold text-purple-600">Selected</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ethers } from 'ethers'
import { MyERC721Token } from '@/artifacts/MyERC721Token'
import { useWallet } from '@/hooks/useWallet'
import { useLocalContracts } from '@/hooks/useLocalContracts'

const collectionName = ref('')
const collectionSymbol = ref('')
const baseURI = ref('')
const isDeploying = ref(false)
const lastDeployedAddress = ref('')
const selectedAddress = ref('')
const error = ref('')

const { signer } = useWallet()
const { addContract, getContractsByType } = useLocalContracts()

const userERC721s = computed(() => getContractsByType('ERC721'))

const selectContract = (address: string) => {
  selectedAddress.value = address
  console.log('Selected contract for operations:', address)
}

const deployNFT = async () => {
  if (!signer.value) {
    error.value = 'Please connect your wallet first.'
    return
  }

  isDeploying.value = true
  lastDeployedAddress.value = ''
  error.value = ''

  try {
    const factory = new ethers.ContractFactory(
      MyERC721Token.abi, 
      MyERC721Token.bytecode, 
      signer.value
    )
    
    const contract = await factory.deploy(collectionName.value, collectionSymbol.value, baseURI.value || '')
    await contract.waitForDeployment()
    
    const address = await contract.getAddress()
    lastDeployedAddress.value = address
    
    addContract({
      contractAddress: address,
      name: collectionName.value,
      symbol: collectionSymbol.value,
      tokenType: 'ERC721',
      timestamp: Date.now()
    })

    collectionName.value = ''
    collectionSymbol.value = ''
    baseURI.value = ''
  } catch (err: any) {
    console.error('Error deploying NFT:', err)
    error.value = err.message || 'Error deploying NFT. See console for details.'
  } finally {
    isDeploying.value = false
  }
}
</script>

// Web-Fundamentals/Web3/DappProject/frontend/src/modules/deploy/DeployERC721.tsx
import { useState, useEffect } from 'react'
import { useAccount } from 'wagmi'

import { useFactoryDeploy } from '../../hooks/useFactoryDeploy'
import { useLocalContracts } from '../../hooks/useLocalContracts'
import { BatchMintForm } from '../../components/BatchMintForm'
import { BatchTransferForm } from '../../components/BatchTransferForm'

export const DeployERC721 = () => {
    const { isConnected } = useAccount()
    const [name, setName] = useState('')
    const [symbol, setSymbol] = useState('')
    const [baseURI, setBaseURI] = useState('')
    const [selectedContract, setSelectedContract] = useState('')

    // Use local contracts hook
    const { addContract, getContractsByType } = useLocalContracts()
    const userERC721s = getContractsByType('ERC721')

    const {
        deployERC721,
        isPending,
        isConfirming,
        isConfirmed,
        contractAddress,
        txHash,
        error,
    } = useFactoryDeploy()

    // Listen for successful deployment to save to local storage
    useEffect(() => {
        if (isConfirmed && contractAddress && name && symbol) {
            addContract({
                contractAddress,
                name,
                symbol,
                tokenType: 'ERC721',
                timestamp: Date.now()
            })
        }
    }, [isConfirmed, contractAddress, name, symbol])

    const handleDeploy = () => {
        if (!name || !symbol) return
        setSelectedContract('')
        deployERC721(name, symbol, baseURI)
    }

    if (!isConnected) {
        return (
            <div className="text-center p-8 bg-gray-50 rounded-xl border-2 border-dashed border-gray-200">
                <p className="text-gray-500">Please connect your wallet to deploy contracts</p>
            </div>
        )
    }

    return (
        <div className="space-y-6 max-w-2xl mx-auto">
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Deploy ERC721 NFT Collection</h3>

                <div className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Collection Name
                        </label>
                        <input
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            placeholder="e.g. My NFT Collection"
                            className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Symbol
                        </label>
                        <input
                            type="text"
                            value={symbol}
                            onChange={(e) => setSymbol(e.target.value)}
                            placeholder="e.g. MNFT"
                            className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Base URI (Optional)
                        </label>
                        <input
                            type="text"
                            value={baseURI}
                            onChange={(e) => setBaseURI(e.target.value)}
                            placeholder="e.g. https://api.mysite.com/metadata/"
                            className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900"
                        />
                        <p className="mt-1 text-xs text-gray-500">
                            The base URL for token metadata. You can set this later.
                        </p>
                    </div>

                    <button
                        onClick={handleDeploy}
                        disabled={isPending || isConfirming || !name || !symbol}
                        className={`w-full py-3 px-4 rounded-xl text-white font-medium transition-all transform active:scale-[0.99]
              ${isPending || isConfirming
                                ? 'bg-indigo-400 cursor-not-allowed'
                                : 'bg-indigo-600 hover:bg-indigo-700 hover:shadow-md'
                            }`}
                    >
                        {isPending ? 'Confirm in Wallet...' : isConfirming ? 'Deploying...' : 'Deploy NFT Collection'}
                    </button>

                    {error && (
                        <div className="p-4 bg-red-50 text-red-700 rounded-lg text-sm">
                            <p className="font-medium">Error deploying contract:</p>
                            <p>{error?.message}</p>
                        </div>
                    )}

                    {isConfirmed && contractAddress && (
                        <div className="p-4 bg-green-50 text-green-700 rounded-lg text-sm">
                            <p className="font-medium">Contract Deployed Successfully!</p>
                            <p className="mt-1 break-all">Address: {contractAddress}</p>
                            <p className="mt-1 break-all text-xs text-green-600">Tx: {txHash}</p>
                        </div>
                    )}

                    <div className="h-px bg-gray-100 my-6"></div>

                    {/* Contract Selector Section */}
                    <div className="space-y-4">
                        <h4 className="text-md font-medium text-gray-900">Manage Your ERC721 Collections</h4>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Select Deployed Contract
                            </label>
                            <select
                                value={selectedContract || (isConfirmed ? contractAddress : '')}
                                onChange={(e) => setSelectedContract(e.target.value)}
                                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900 bg-white"
                            >
                                <option value="">-- Choose a collection --</option>
                                {userERC721s.map((deployment) => (
                                    <option key={deployment.contractAddress} value={deployment.contractAddress}>
                                        {deployment.name} ({deployment.symbol}) - {deployment.contractAddress.slice(0, 6)}...{deployment.contractAddress.slice(-4)}
                                    </option>
                                ))}
                                {isConfirmed && contractAddress && !userERC721s.find(c => c.contractAddress === contractAddress) && (
                                    <option value={contractAddress}>
                                        {name} ({symbol}) - {contractAddress.slice(0, 6)}...{contractAddress.slice(-4)} (Just Deployed)
                                    </option>
                                )}
                            </select>
                        </div>

                        {(selectedContract || (isConfirmed && contractAddress)) && (
                            <div className="p-4 bg-indigo-50 border border-indigo-100 rounded-xl space-y-4">
                                <div className="flex justify-between items-center">
                                    <span className="text-sm font-medium text-indigo-900">
                                        Active Contract: {(selectedContract || contractAddress).slice(0, 10)}...{(selectedContract || contractAddress).slice(-8)}
                                    </span>
                                    <button
                                        onClick={() => {
                                            const addr = (selectedContract || contractAddress);
                                            navigator.clipboard.writeText(addr);
                                        }}
                                        className="text-xs text-indigo-600 hover:text-indigo-800 font-medium"
                                    >
                                        Copy Address
                                    </button>
                                </div>

                                <div className="space-y-6">
                                    <div>
                                        <h5 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                                            <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full mr-2"></span>
                                            Batch Minting
                                        </h5>
                                        <BatchMintForm
                                            contractAddress={selectedContract || contractAddress}
                                            tokenType="ERC721"
                                        />
                                    </div>

                                    <div className="h-px bg-indigo-100"></div>

                                    <div>
                                        <h5 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                                            <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full mr-2"></span>
                                            Batch Transfer
                                        </h5>
                                        <BatchTransferForm
                                            contractAddress={selectedContract || contractAddress}
                                            tokenType="ERC721"
                                        />
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    )
}
