// Web-Fundamentals/Web3/DappProject2.0/frontend/src/components/DeployERC20.vue
<template>
  <div class="bg-white shadow rounded-lg p-6 max-w-2xl mx-auto">
    <h3 class="text-xl font-bold mb-6 text-gray-900">Deploy ERC20 Token</h3>
    <form @submit.prevent="deployToken" class="space-y-4">
      <div>
        <label for="tokenName" class="block text-sm font-medium text-gray-700 mb-1">Token Name</label>
        <input 
          type="text" 
          id="tokenName" 
          v-model="tokenName" 
          placeholder="e.g. My Token"
          class="block w-full px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-gray-900 placeholder-gray-400" 
          required
        >
      </div>
      <div>
        <label for="tokenSymbol" class="block text-sm font-medium text-gray-700 mb-1">Token Symbol</label>
        <input 
          type="text" 
          id="tokenSymbol" 
          v-model="tokenSymbol" 
          placeholder="e.g. MTK"
          class="block w-full px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-gray-900 placeholder-gray-400" 
          required
        >
      </div>
      <div>
        <label for="initialSupply" class="block text-sm font-medium text-gray-700 mb-1">Initial Supply</label>
        <input 
          type="number" 
          id="initialSupply" 
          v-model="initialSupply" 
          placeholder="1000000"
          class="block w-full px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-gray-900 placeholder-gray-400" 
          required
        >
      </div>
      <div>
        <label for="decimals" class="block text-sm font-medium text-gray-700 mb-1">Decimals</label>
        <input 
          type="number" 
          id="decimals" 
          v-model="decimals" 
          placeholder="18"
          class="block w-full px-4 py-2 bg-white border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-gray-900 placeholder-gray-400" 
          required
        >
      </div>
      <button 
        type="submit" 
        :disabled="isDeploying"
        class="w-full flex justify-center py-3 px-4 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-indigo-400 transition-colors"
      >
        {{ isDeploying ? 'Deploying...' : 'Deploy' }}
      </button>
    </form>

    <!-- Success Message -->
    <div v-if="lastDeployedAddress" class="mt-6 p-4 bg-green-50 border border-green-200 rounded-lg">
      <p class="text-green-800 font-medium">Deployment Success!</p>
      <p class="text-green-600 text-sm break-all font-mono mt-1">{{ lastDeployedAddress }}</p>
    </div>

    <!-- Local History -->
    <div v-if="userERC20s.length > 0" class="mt-10 pt-6 border-t border-gray-100">
      <h4 class="text-lg font-semibold text-gray-900 mb-4">Your Deployed Contracts (Local)</h4>
      <div class="space-y-3">
        <div 
          v-for="contract in userERC20s" 
          :key="contract.contractAddress"
          @click="selectContract(contract.contractAddress)"
          class="p-4 rounded-xl border border-gray-200 hover:border-indigo-400 hover:bg-indigo-50 cursor-pointer transition-all flex justify-between items-center"
          :class="{ 'border-indigo-600 bg-indigo-50': selectedAddress === contract.contractAddress }"
        >
          <div class="flex flex-col">
            <span class="text-gray-900 font-medium">{{ contract.name }} ({{ contract.symbol }})</span>
            <span class="text-xs text-gray-500 font-mono">{{ contract.contractAddress }}</span>
          </div>
          <span v-if="selectedAddress === contract.contractAddress" class="text-xs font-semibold text-indigo-600">Selected</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, toRaw } from 'vue'
import { ethers } from 'ethers'
import { MyERC20Token } from '@/artifacts/MyERC20Token'
import { useWallet } from '@/hooks/useWallet'
import { useLocalContracts } from '@/hooks/useLocalContracts'

const tokenName = ref('')
const tokenSymbol = ref('')
const initialSupply = ref(0)
const decimals = ref(18)
const isDeploying = ref(false)
const lastDeployedAddress = ref('')
const selectedAddress = ref('')

const { signer } = useWallet()
const { addContract, getContractsByType } = useLocalContracts()

const userERC20s = computed(() => getContractsByType('ERC20'))

const selectContract = (address: string) => {
  selectedAddress.value = address
  console.log('Selected contract for operations:', address)
}

const deployToken = async () => {
  if (!signer.value) {
    alert('Please connect your wallet first.')
    return
  }

  isDeploying.value = true
  lastDeployedAddress.value = ''

  try {
    const factory = new ethers.ContractFactory(
      MyERC20Token.abi, 
      MyERC20Token.bytecode, 
      toRaw(signer.value)
    )
    
    const initParams = [
      tokenName.value, 
      tokenSymbol.value, 
      initialSupply.value.toString(), 
      decimals.value
    ]
    
    const contract = await factory.deploy(...initParams)
    await contract.waitForDeployment()
    
    const address = await contract.getAddress()
    lastDeployedAddress.value = address
    
    // Save to local storage
    addContract({
      contractAddress: address,
      name: tokenName.value,
      symbol: tokenSymbol.value,
      tokenType: 'ERC20',
      timestamp: Date.now()
    })

    // Reset form
    tokenName.value = ''
    tokenSymbol.value = ''
    initialSupply.value = 0
  } catch (error) {
    console.error('Error deploying token:', error)
    alert('Error deploying token. See console for details.')
  } finally {
    isDeploying.value = false
  }
}
</script>

// Web-Fundamentals/Web3/DappProject/frontend/src/modules/deploy/DeployERC20.tsx
import { useState, useEffect } from 'react'
import { useAccount } from 'wagmi'

import { useFactoryDeploy } from '../../hooks/useFactoryDeploy'
import { useLocalContracts } from '../../hooks/useLocalContracts' // Changed from useTokenFactory
import { BatchMintForm } from '../../components/BatchMintForm'
import { BatchTransferForm } from '../../components/BatchTransferForm'

export const DeployERC20 = () => {
    const { isConnected } = useAccount()
    const [name, setName] = useState('')
    const [symbol, setSymbol] = useState('')
    const [supply, setSupply] = useState('')
    const [decimals, setDecimals] = useState('18')
    const [selectedContract, setSelectedContract] = useState('')

    // Use local contracts hook
    const { addContract, getContractsByType } = useLocalContracts()
    const userERC20s = getContractsByType('ERC20')

    const {
        deployERC20,
        isPending,
        isConfirming,
        isConfirmed,
        contractAddress,
        txHash,
        error,
    } = useFactoryDeploy()

    // Listen for successful deployment to save to local storage
    useEffect(() => {
        if (isConfirmed && contractAddress && name && symbol) {
            addContract({
                contractAddress,
                name,
                symbol,
                tokenType: 'ERC20',
                timestamp: Date.now()
            })
        }
    }, [isConfirmed, contractAddress, name, symbol]) // Dependencies to trigger save

    const handleDeploy = () => {
        if (!name || !symbol || !supply) return
        setSelectedContract('') // Clear selection on new deployment
        deployERC20(name, symbol, BigInt(supply || 0), Number(decimals))
    }

    if (!isConnected) {
        return (
            <div className="text-center p-8 bg-gray-50 rounded-xl border-2 border-dashed border-gray-200">
                <p className="text-gray-500">Please connect your wallet to deploy contracts</p>
            </div>
        )
    }

    return (
        <div className="space-y-6 max-w-2xl mx-auto">
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">Deploy ERC20 Token</h3>

                <div className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Token Name
                        </label>
                        <input
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            placeholder="e.g. My Token"
                            className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900 placeholder-gray-500"
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Token Symbol
                        </label>
                        <input
                            type="text"
                            value={symbol}
                            onChange={(e) => setSymbol(e.target.value)}
                            placeholder="e.g. MTK"
                            className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900 placeholder-gray-500"
                        />
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Initial Supply (Tokens)
                            </label>
                            <input
                                type="number"
                                value={supply}
                                onChange={(e) => setSupply(e.target.value)}
                                placeholder="e.g. 1000000"
                                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900 placeholder-gray-500"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Decimals
                            </label>
                            <input
                                type="number"
                                value={decimals}
                                onChange={(e) => setDecimals(e.target.value)}
                                placeholder="18"
                                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900 placeholder-gray-500"
                            />
                        </div>
                    </div>

                    <button
                        onClick={handleDeploy}
                        disabled={isPending || isConfirming || !name || !symbol || !supply}
                        className={`w-full py-3 px-4 rounded-xl text-white font-medium transition-all transform active:scale-[0.99]
              ${isPending || isConfirming
                                ? 'bg-indigo-400 cursor-not-allowed'
                                : 'bg-indigo-600 hover:bg-indigo-700 hover:shadow-md'
                            }`}
                    >
                        {isPending ? 'Confirm in Wallet...' : isConfirming ? 'Deploying...' : 'Deploy Token'}
                    </button>

                    {error && (
                        <div className="p-4 bg-red-50 text-red-700 rounded-lg text-sm">
                            <p className="font-medium">Error deploying contract:</p>
                            <p>{error?.message}</p>
                        </div>
                    )}

                    {isConfirmed && contractAddress && (
                        <div className="p-4 bg-green-50 text-green-700 rounded-lg text-sm">
                            <p className="font-medium">Contract Deployed Successfully!</p>
                            <p className="mt-1 break-all">Address: {contractAddress}</p>
                            <p className="mt-1 break-all text-xs text-green-600">Tx: {txHash}</p>
                        </div>
                    )}

                    <div className="h-px bg-gray-100 my-6"></div>

                    {/* Contract Selector Section */}
                    <div className="space-y-4">
                        <h4 className="text-md font-medium text-gray-900">Manage Your ERC20 Contracts</h4>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Select Deployed Contract
                            </label>
                            <select
                                value={selectedContract || (isConfirmed ? contractAddress : '')}
                                onChange={(e) => setSelectedContract(e.target.value)}
                                className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent outline-none transition-all text-gray-900 bg-white"
                            >
                                <option value="">-- Choose a contract --</option>
                                {userERC20s.map((deployment) => (
                                    <option key={deployment.contractAddress} value={deployment.contractAddress}>
                                        {deployment.name} ({deployment.symbol}) - {deployment.contractAddress.slice(0, 6)}...{deployment.contractAddress.slice(-4)}
                                    </option>
                                ))}
                                {isConfirmed && contractAddress && !userERC20s.find(c => c.contractAddress === contractAddress) && (
                                    <option value={contractAddress}>
                                        {name} ({symbol}) - {contractAddress.slice(0, 6)}...{contractAddress.slice(-4)} (Just Deployed)
                                    </option>
                                )}
                            </select>
                        </div>

                        {(selectedContract || (isConfirmed && contractAddress)) && (
                            <div className="p-4 bg-indigo-50 border border-indigo-100 rounded-xl space-y-4">
                                <div className="flex justify-between items-center">
                                    <span className="text-sm font-medium text-indigo-900">
                                        Active Contract: {(selectedContract || contractAddress).slice(0, 10)}...{(selectedContract || contractAddress).slice(-8)}
                                    </span>
                                    <button
                                        onClick={() => {
                                            const addr = (selectedContract || contractAddress);
                                            navigator.clipboard.writeText(addr);
                                        }}
                                        className="text-xs text-indigo-600 hover:text-indigo-800 font-medium"
                                    >
                                        Copy Address
                                    </button>
                                </div>

                                <div className="space-y-6">
                                    <div>
                                        <h5 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                                            <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full mr-2"></span>
                                            Batch Minting
                                        </h5>
                                        <BatchMintForm
                                            contractAddress={selectedContract || contractAddress}
                                            tokenType="ERC20"
                                        />
                                    </div>

                                    <div className="h-px bg-indigo-100"></div>

                                    <div>
                                        <h5 className="text-sm font-semibold text-gray-900 mb-3 flex items-center">
                                            <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full mr-2"></span>
                                            Batch Transfer
                                        </h5>
                                        <BatchTransferForm
                                            contractAddress={selectedContract || contractAddress}
                                            tokenType="ERC20"
                                        />
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    )
}
